name: CI

on:
    push:
        branches-ignore:
            - "dependabot/**"
    workflow_dispatch:

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Setup bun
              uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
              with:
                bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Fix biome issues
              run: bun run biome:write

            - name: Commit changes
              run: |
                  git config user.name github-actions[bot]
                  git config user.email github-actions[bot]@users.noreply.github.com
                  git commit -am "refactor(GHActionbot): :art: formatted & linting & organized imports with biome" || true

            - name: Push changes
              uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}

            - name: Check if all issues are fixed with biome
              run: bun run biome:ci

            - name: Test
              run: bun test

            - name: Build
              run: bun run build
