name: Dependabot update from npm to bun

on:
  pull_request:
    paths:
      - "package.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-bun-lockb:
    name: "Update bun.lockb"
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update lock file
        run: |
          bun install 

      - name: Test
        run: bun test 

      - name: Build
        run: bun run build
