name: Dependabot CI

on:
  pull_request:
    paths:
      - "package.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    name: "Dependabot CI"
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: Update lock file
        run: |
          bun install 

      - name: Test
        run: bun test 

      - name: Build
        run: bun run build
