name: Release Obsidian plugin

on:
    workflow_run: # only release if Linter finds no errors
        workflows:
            - "Linter"
        types:
            - completed
    push:
        tags:
            - "*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Build plugin
              run: |
                  bun install
                  bun run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  notes_file="release-notes.md"
                  notes_option=""
                  if [ -f "$notes_file" ]; then
                      notes_option="--notes-file=$notes_file"
                  fi

                  gh release create "$tag" \
                      --title="$tag" \
                      $notes_option \
                      main.js manifest.json styles.css
